# Generated by Django 3.0.3 on 2020-09-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0002_auto_20200923_2030'),
        ('Petservice', '0002_auto_20200922_2009'),
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='P_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PetShop.Petshop'),
        ),
        migrations.AddField(
            model_name='payment',
            name='S_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Petservice.Service'),
        ),
    ]
