# Generated by Django 3.0.3 on 2020-09-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petshop',
            old_name='product_name',
            new_name='name',
        ),
    ]
