# Generated by Django 3.0.3 on 2020-09-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('service_type', models.CharField(max_length=30)),
                ('service_cost', models.CharField(max_length=20)),
            ],
        ),
    ]
