# Generated by Django 3.0.3 on 2020-09-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Petservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_type',
            new_name='type',
        ),
    ]
